name: edu_quiz_app
description: "A G.C.E. O/L Quiz Application for Sri Lankan Students."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management (ප්‍රාන්ත කළමනාකරණය සඳහා)
  provider: ^6.1.1

  # Firebase Core (Firebase Initialize කිරීමට)
  firebase_core: ^3.6.0

  # Firebase Authentication (Email/Password Login සඳහා)
  firebase_auth: ^5.3.1

  # Cloud Firestore (දත්ත ගබඩාව සඳහා)
  cloud_firestore: ^5.4.4

  # Icons and Design elements (අයිකන සඳහා)
  cupertino_icons: ^1.0.6
  image_picker: ^1.2.2
  firebase_storage: ^12.4.10
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
